name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv pip install --system -r requirements.txt

    - name: Run linting
      run: |
        ruff format
        ruff check --fix

    - name: Run tests
      run: python -m pytest tests/ -v

    - name: Build Docker image
      run: docker build -t ticket-urgency-classifier .

    - name: Test Docker image
      run: |
        docker run -d --name test-container -p 8000:8000 ticket-urgency-classifier
        sleep 10
        curl -f http://localhost:8000/docs || exit 1
        docker stop test-container
        docker rm test-container

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/ticket-urgency-classifier:latest
          ${{ secrets.DOCKER_USERNAME }}/ticket-urgency-classifier:${{ github.sha }}
